# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError
# Set Kotlin daemon to use Java 21 as well
kotlin.daemon.jvm.options=-Xmx2048m -Dorg.gradle.java.home=C:\\jdk21
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.r8.runInSeparateProcess=true
android.builtInKotlin=false
android.newDsl=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
